# Nombre del archivo zip de salida
OUTPUT_ZIP=proyecto_src.zip

# Directorio de la carpeta src del proyecto
SRC_DIR=./path_to_your_project/src

# Comando para comprimir los archivos
zip:
    zip -r $(OUTPUT_ZIP) $(SRC_DIR)

# Comando para limpiar (eliminar el archivo zip)
clean:
    rm -f $(OUTPUT_ZIP)
